version: '3.5'

services:
  react-app:
    container_name: wunder-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: 'yarn start'
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
